---
- name: "[﬒ dotfiles] Download Vundle (vi bundle manager)"
  ansible.builtin.git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    version: v0.10.2
  changed_when: false

- name: "[﬒ dotfiles] Setup and install Vundle"
  ansible.builtin.shell:
    cmd: echo | echo | vim +PluginInstall +qall &>/dev/null
  changed_when: false
